- name: Install zsh config
  copy:
    src: "{{ item }}"
    dest: /etc/zsh/
  become: yes
  loop:
    - etc/zsh/zshrc
    - etc/zsh/zprofile
    - etc/zsh/antigen.zsh
    - etc/zsh/command-not-found.zsh
    - etc/zsh/myprompt.zsh
    - etc/zsh/dirstack.zsh
    - etc/zsh/undistract-me.zsh

- name: Touch .zshrc
  copy:
    content: ""
    dest: /home/{{ username }}/.zshrc
    force: no
  become: yes
  become_user: "{{ username }}"

- name: Create zsh dircache
  file:
    path: /home/{{ username }}/.cache/zsh/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Touch .zshrc
  copy:
    content: ""
    dest: /root/.zshrc
    force: no
  become: yes

- name: Create zsh dircache
  file:
    path: /root/.cache/zsh/
    state: directory
  become: yes

- name: Set shell to zsh
  command: usermod --shell /bin/zsh {{ username }}
  become: yes
  changed_when: false
  when: shell == 'zsh'
