---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - zsh.install
  - import_tasks: configure.yml
    tags:
      - configure
      - zsh.configure
  tags:
    - zsh

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - zsh.uninstall
