---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - autorandr.install
  - import_tasks: configure.yml
    tags:
      - configure
      - autorandr.configure
  tags:
    - autorandr
