---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - autorandr.install
  - import_tasks: configure.yml
    tags:
      - configure
      - autorandr.configure
  tags:
    - autorandr
    - gui

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - autorandr.uninstall
