---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - pip.install
  tags:
    - pip
    - python

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - pip.uninstall
