- name: Ensure qtile config dir exists
  file:
    path: /home/{{ username }}/.config/qtile/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Configure qtile
  template:
    src: HOME/.config/qtile/config.py.j2
    dest: /home/{{ username }}/.config/qtile/config.py
    mode: '0755'
  become: yes
  become_user: "{{ username }}"

- name: Configure xinitrc
  copy:
    src: HOME/.xinitrc
    dest: /home/{{ username }}/.xinitrc
  become: yes
  become_user: "{{ username }}"
