- name: Install qtile
  package:
    name:
      - qtile
  become: yes
  when: ansible_distribution == 'Archlinux'

- name: Install qtile
  pip:
    name:
      - qtile
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install python wheel
  pip:
    name:
      - wheel
  become: yes

- name: Install libiw
  package:
    name:
      - libiw-dev
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install iwlib
  pip:
    name:
      - iwlib
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install iwlib
  package:
    name:
      - iw
      - python-iwlib
  become: yes
  when: ansible_distribution == 'Archlinux'

- name: Install qtile python dependencies
  pip:
    name:
      - psutil
  become: yes
