- name: Install qtile
  package:
    name:
      - qtile
  become: yes
  when: ansible_distribution == 'Archlinux'

- name: Install qtile
  pip:
    name:
      - qtile
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install qtile dependencies
  package:
    name: "{{ qtile_deps }}"
  become: yes
  when: qtile_deps

- name: Install qtile python dependencies
  pip:
    name: "{{ qtile_python_deps }}"
  become: yes
  when: qtile_python_deps
