- import_tasks: ../../_common/install_xorg.yml

- name: Install qtile
  package:
    name:
      - qtile
  become: yes

- name: Install qtile python dependencies
  pip:
    name:
      - psutil
      - iwlib
