- name: Install alacritty
  package:
    name:
      - alacritty
  become: yes
  when: ansible_distribution == 'Archlinux'

- name: Install alacritty
  apt:
    deb: https://github.com/alacritty/alacritty/releases/download/v0.4.2/Alacritty-v0.4.2-ubuntu_18_04_amd64.deb
  become: yes
  when: ansible_os_family == 'Debian'

