- block:
  - import_tasks: install.yml
    tags:
      - install
      - alacritty.install
  - import_tasks: configure.yml
    tags:
      - configure
      - alacritty.configure
  tags:
    - alacritty
    - gui

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - alacritty.uninstall
