---
- name: work
  hosts: all
  vars_files:
    - vars.yml
  roles:
    - common
    - zsh
    - git
    - neovim
    - neomutt
    - tmux
    - i3
    - xkb
    - qutebrowser
    - wifi
    - virtualization
