---
- name: main
  hosts: all
  vars_files:
    - vars.yml
  module_defaults:
    copy:
      backup: yes
    template:
      backup: yes
    lineinfile:
      backup: yes
  roles:
    - common
    - shell/all
    - git
    - neovim
    - pass
    - dunst
    - mail/neomutt
    - mail/offlineimap
    - mail/msmtp
    - tmux
    - autorandr
    - wm/qtile
    - terminal/alacritty
    - xkb
    - qutebrowser
    - wifi
    - bluetooth
    - virtualization
