---
- name: work
  hosts: all
  vars_files:
    - vars.yml
  module_defaults:
    copy:
      backup: yes
    template:
      backup: yes
    lineinfile:
      backup: yes
  roles:
    - common
    - zsh
    - git
    - neovim
    - pass
    - neomutt
    - tmux
    - i3
    - qtile
    - xkb
    - qutebrowser
    - wifi
    - virtualization
