---
- name: main
  hosts: all
  module_defaults:
    copy:
      backup: yes
    template:
      backup: yes
    lineinfile:
      backup: yes
  roles:
    - common
    - shell/all
    - git
    - neovim
    - pass
    - dunst
    - mail/notmuch
    - mail/neomutt
    - mail/offlineimap
    - mail/msmtp
    - tmux
    - autorandr
    - syncthing
    - wm/qtile
    - terminal/alacritty
    - xkb
    - qutebrowser
    - wifi
    - bluetooth
    - virtualization

# TODO add notification for failed services!
# TODO add calendar sync (vdirsyncer?)
# TODO add calendar app
# TODO add meeting invite converter/importer
