- name: Create .config/notmuch/default directory
  file:
    path: /home/{{ username }}/.config/notmuch/default/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Email notification script
  copy:
    src: HOME/.config/notmuch/default/notmuch.sh
    dest: /home/{{ username }}/.config/notmuch/default/notmuch.sh
    mode: '0700'
  become: yes
  become_user: "{{ username }}"

- name: Configure notmuch
  template:
    src: HOME/.config/notmuch/default/config.j2
    dest: /home/{{ username }}/.config/notmuch/default/config
    mode: '0600'
  become: yes
  become_user: "{{ username }}"
