---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - notmuch.install
  - import_tasks: configure.yml
    tags:
      - configure
      - notmuch.configure
  tags:
    - notmuch
    - mail

- import_tasks: clean.yml
  tags:
    - never
    - clean
    - notmuch.clean

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - notmuch.uninstall
