- name: Set qutebrowser as default web browser
  command: xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop
  become: yes
  become_user: "{{ username }}"
  when: ansible_distribution == 'Archlinux'
    #TODO fix this for debian as well

- name: Ensure qutebrowser config dir exists
  file:
    dest: /home/{{ username }}/.config/qutebrowser/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Configure qutebrowser
  copy:
    src: HOME/.config/qutebrowser/config.py
    dest: /home/{{ username }}/.config/qutebrowser/config.py
  become: yes
  become_user: "{{ username }}"

- name: Install userscripts
  copy:
    src: HOME/.config/qutebrowser/greasemonkey/youtube-ad-blocker.js
    dest: /home/{{ username }}/.config/qutebrowser/greasemonkey/
  become: yes
  become_user: "{{ username }}"

    # TODO qute dmenu
