- name: Install wifi tools
  package:
    name:
      - networkmanager
    state: present
  become: yes
  when: ansible_distribution == 'Archlinux'

- name: Install wifi tools
  package:
    name:
      - network-manager
    state: present
  become: yes
  when: ansible_os_family == 'Debian'
