- name: Install bluetooth tools
  package:
    name: "{{ bluez }}"
    state: present
  become: yes

- name: Install pulseaudio bluetooth support
  package:
    name: "{{ pulseaudio_bluetooth }}"
    state: present
  become: yes
  tags:
    - sound
