- name: Ensure i3 config dir exists
  file:
    path: /home/{{ username }}/.config/i3/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Configure i3
  copy:
    src: HOME/.config/i3/config
    dest: /home/{{ username }}/.config/i3/config
  become: yes
  become_user: "{{ username }}"

- name: Configure i3blocks bottom
  copy:
    src: HOME/.i3blocks_bottom.conf
    dest: /home/{{ username }}/.i3blocks_bottom.conf
  become: yes
  become_user: "{{ username }}"

- name: Configure i3blocks top
  copy:
    src: HOME/.i3blocks_top.conf
    dest: /home/{{ username }}/.i3blocks_top.conf
  become: yes
  become_user: "{{ username }}"

- name: Configure xinitrc
  copy:
    src: HOME/.xinitrc
    dest: /home/{{ username }}/.xinitrc
  become: yes
  become_user: "{{ username }}"
