- import_tasks: ../../_common/install_xorg.yml

- name: Install graphical environment
  package:
    name:
      - i3-wm
      - i3blocks
      - rofi
      - rxvt-unicode
    state: present
  become: yes
