---
- block:
  - import_tasks: ../../_common/main.yml

  - import_tasks: install.yml
    tags:
      - install
      - i3.install
  - import_tasks: configure.yml
    tags:
      - configure
      - i3.configure
  tags:
    - i3
    - gui
