---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - i3.install
  - import_tasks: configure.yml
    tags:
      - configure
      - i3.configure
  tags:
    - wm
    - i3
    - gui

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - i3.uninstall
