- name: Create .config/offlineimap directory
  file:
    path: /home/{{ username }}/.config/offlineimap/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Auth script
  copy:
    src: HOME/.config/offlineimap/auth.py
    dest: /home/{{ username }}/.config/offlineimap/auth.py
    mode: '0700'
  become: yes
  become_user: "{{ username }}"

- name: Email notification script
  copy:
    src: HOME/.config/offlineimap/notify-new.sh
    dest: /home/{{ username }}/.config/offlineimap/notify-new.sh
    mode: '0700'
  become: yes
  become_user: "{{ username }}"

- name: Configure offlineimap
  template:
    src: HOME/.config/offlineimap/config.j2
    dest: /home/{{ username }}/.config/offlineimap/config
    mode: '0600'
  become: yes
  become_user: "{{ username }}"

- name: Enable offlineimap service
  systemd:
    name: offlineimap@{{ item.account_name }}
    scope: user
    enabled: yes
    state: restarted
  become: yes
  become_user: "{{ username }}"
  loop: "{{ email_accounts }}"
