---
- block:
  - import_tasks: prepare.yml
    tags:
      - install
      - offlineimap.prepare
  - import_tasks: install.yml
    tags:
      - install
      - offlineimap.install
  - import_tasks: configure.yml
    tags:
      - configure
      - offlineimap.configure
  tags:
    - offlineimap
    - mail

- import_tasks: clean.yml
  tags:
    - never
    - clean
    - offlineimap.clean

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - offlineimap.uninstall
