---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - offlineimap.install
  - import_tasks: configure.yml
    tags:
      - configure
      - offlineimap.configure
  tags:
    - offlineimap

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - offlineimap.uninstall
