---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - fish.install
  - import_tasks: configure.yml
    tags:
      - configure
      - fish.configure
  tags:
    - fish

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - fish.uninstall
