---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - pass.install
  - import_tasks: configure.yml
    tags:
      - configure
      - pass.configure
  tags:
    - pass

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - pass.uninstall
