- name: Install rofi
  package:
    name:
      - rofi
    state: present
  become: yes
  tags: gui

- name: Install rofimoji
  package:
    name:
      - rofimoji
      - xdotool
    state: present
  become: yes
  tags:
    - gui
    - emoji
