- name: Install rofi
  package:
    name:
      - rofi
    state: present
  become: yes
  tags: gui
    # TODO rofi as dmenu

- name: Install rofimoji dependencies
  package:
    name:
      - xdotool
    state: present
  become: yes
  tags:
    - gui
    - emoji

- name: Install rofimoji
  community.general.pipx:
    name: rofimoji
    state: present
  become: yes
  become_user: "{{ username }}"
  tags:
    - gui
    - emoji
