- name: Install fonts
  package:
    name:
      - "{{ dejavu }}"
    state: present
  become: yes
  tags:
    - gui

- name: Install emoji font
  package:
    name:
      - "{{ emoji_font }}"
    state: present
  become: yes
  tags:
    - gui
    - emoji

- name: Configure fonts
  copy:
    src: etc/fonts/local.conf
    dest: /etc/fonts/local.conf
  become: yes
  tags:
    - gui
    - emoji
