- name: Install xorg
  block:
    - name: Install xorg
      package:
        name:
          - xorg-server
          - xorg-xinit
          - xorg-xev
          - xorg-xrandr
        state: present
      become: yes
      when: ansible_distribution == 'Archlinux'

    - name: Install xorg
      package:
        name:
          - xserver-xorg
        state: present
      become: yes
      when: ansible_os_family == 'Debian'
  tags:
    - gui
