- name: Install fonts
  package:
    name:
      - "{{ dejavu }}"
    state: present
  become: yes
  tags:
    - gui

- name: Install Nerd Fonts (symbols)
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/DejaVuSansMono.zip
    dest: "{{ font_dir }}"
    remote_src: yes
  become: yes

- name: Install emoji font
  package:
    name:
      - "{{ emoji_font }}"
    state: present
  become: yes
  tags:
    - gui
    - emoji

- name: Configure fonts
  copy:
    src: etc/fonts/local.conf
    dest: "{{ fontconfig }}"
  become: yes
  tags:
    - gui
    - emoji
