---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  tags:
    - always

- block:
  - import_tasks: configure.yml
    tags:
      - configure
      - xkb.configure
  tags:
    - xkb
    - gui
