- name: Install gitconfig
  template:
    src: HOME/.gitconfig.j2
    dest: /home/{{ username }}/
  become: yes
  become_user: "{{ username }}"

- name: Create git template dir
  file:
    path: /home/{{ username }}/.git_template/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Create git hooks dir
  file:
    path: /home/{{ username }}/.git_template/hooks/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Install git hooks
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/
  become: yes
  become_user: "{{ username }}"
  loop:
    - HOME/.git_template/hooks/ctags
    - HOME/.git_template/hooks/post-checkout
    - HOME/.git_template/hooks/post-commit
    - HOME/.git_template/hooks/post-merge
    - HOME/.git_template/hooks/post-rewrite

- name: Install global gitignore
  copy:
    src: HOME/.gitignore
    dest: /home/{{ username }}/
  become: yes
  become_user: "{{ username }}"

