---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - git.install
  - import_tasks: configure.yml
    tags:
      - configure
      - git.configure
  tags:
    - git

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - git.uninstall
