- name: Ensure systemd default target dir exists for user
  file:
    dest: /home/{{ username }}/.config/systemd/user/default.target.wants/
    state: directory
  become: yes
  become_user: "{{ username }}"
  tags:
    - systemd

- name: Enable notification service
  file:
    src: /usr/lib/systemd/user/dunst.service
    dest: /home/{{ username }}/.config/systemd/user/default.target.wants/dunst.service
    state: link
  become: yes
  become_user: "{{ username }}"
  tags:
    - systemd

- name: Restart notification service
  systemd:
    name: dunst
    scope: user
    state: restarted
    daemon_reload: yes
  become: yes
  become_user: "{{ username }}"
  failed_when: False
  tags:
    - systemd
