- name: Create .mutt directory
  file:
    path: /home/{{ username }}/.mutt/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Configure mutt
  copy:
    src: HOME/.mutt/muttrc
    dest: /home/{{ username }}/.mutt/muttrc
  become: yes
  become_user: "{{ username }}"

- name: Add mailcap
  copy:
    src: HOME/.mutt/mailcap
    dest: /home/{{ username }}/.mutt/mailcap
  become: yes
  become_user: "{{ username }}"

- name: Configure gmail account in mutt
  template:
    src: HOME/.mutt/gmail.j2
    dest: /home/{{ username }}/.mutt/gmail
  become: yes
  become_user: "{{ username }}"

- name: Gmail authentication script for mutt
  copy:
    src: HOME/.mutt/oauth2.py
    dest: /home/{{ username }}/.mutt/
    mode: '0755'
  become: yes
  become_user: "{{ username }}"
