# TODO install in home dir
- name: Install tmux.conf
  copy:
    src: etc/tmux.conf
    dest: /etc/
  become: yes

- name: Preserve TMUX variable for sudo
  copy:
    src: etc/sudoers.d/tmux
    dest: "{{ sudoers_d }}/tmux"
  become: yes

    # TODO check plugin tag in tmux conf template
- name: Check if TPM is installed
  stat:
    path: /home/{{ username }}/.tmux/plugins/tpm/bin/install_plugins
  register: tpm
  become: yes
  become_user: "{{ username }}"
  tags:
    - plugins
    - tmux.plugins

- name: Install Tmux plugins
  command: /home/{{ username }}/.tmux/plugins/tpm/bin/install_plugins
  become: yes
  become_user: "{{ username }}"
  when: tpm.stat.exists
  tags:
    - plugins
    - tmux.plugins
