---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - tmux.install
  - import_tasks: configure.yml
    tags:
      - configure
      - tmux.configure
  tags:
    - tmux

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - tmux.uninstall
