- name: Create .config/msmtp directory
  file:
    path: /home/{{ username }}/.config/msmtp/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Configure msmtp
  template:
    src: HOME/.config/msmtp/config.j2
    dest: /home/{{ username }}/.config/msmtp/config
    mode: '0600'
  become: yes
  become_user: "{{ username }}"
