---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - msmtp.install
  - import_tasks: configure.yml
    tags:
      - configure
      - msmtp.configure
  tags:
    - msmtp
    - mail

- import_tasks: clean.yml
  tags:
    - never
    - clean
    - msmtp.clean

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - msmtp.uninstall
