---
- block:
  - import_tasks: prepare.yml
    tags:
      - install
      - msmtp.prepare
  - import_tasks: install.yml
    tags:
      - install
      - msmtp.install
  - import_tasks: configure.yml
    tags:
      - configure
      - msmtp.configure
  tags:
    - msmtp

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - msmtp.uninstall
