---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - virtualization.install
  - import_tasks: configure.yml
    tags:
      - configure
      - virtualization.configure
  tags:
    - virtualization

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - virtualization.uninstall
