---
- block:
  - import_tasks: prepare.yml
    tags:
      - install
      - davmail.prepare
  - import_tasks: install.yml
    tags:
      - install
      - davmail.install
  - import_tasks: configure.yml
    tags:
      - configure
      - davmail.configure
  tags:
    - davmail
    - mail

- import_tasks: clean.yml
  tags:
    - never
    - clean
    - davmail.clean

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - davmail.uninstall
