- name: Adjust time
  command: ntpd -gq
  become: yes
  when: ansible_distribution == 'Archlinux'

- name: Update hardware clock
  command: hwclock --systohc
  become: yes
  when: ansible_distribution == 'Archlinux'
  tags:
    - hardware

- name: Create 'wheel' group
  group:
    name: wheel
    state: present
  become: yes
  tags:
    - user
    - sudo

- name: Allow 'wheel' group to sudo
  lineinfile:
    dest: "{{ sudoers_file }}"
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
  when: ansible_distribution != 'FreeBSD'
  become: yes
  tags:
    - user
    - sudo

- name: Create group for {{ username }}
  group:
    name: "{{ username }}"
    state: present
  become: yes
  tags:
    - user

- name: Add user {{ username }}
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    update_password: on_create
    group: "{{ username }}"
    groups: wheel
  become: yes
  tags:
    - user

