- name: Refresh package list
  block:
    - name: pacman -Sy
      community.general.pacman:
        update_cache: yes
      become: yes
      when: ansible_distribution == 'Archlinux'

    - name: apt update
      command: apt update
      become: yes
      when: ansible_os_family == 'Debian'
  tags:
    - update

      # TODO generalize

- name: Upgrade system
  community.general.pacman:
    upgrade: yes
  become: yes
  when: ansible_distribution == 'Archlinux'
  tags:
    - update

      # TODO generalize

- name: Install base-devel
  package:
    name:
      - base
      - base-devel
      - ntp
    state: present
  become: yes
  when: ansible_distribution == 'Archlinux'
    #
      # TODO generalize

- name: Install sudo
  package:
    name:
      - sudo
    state: present
  become: yes
  tags:
    - sudo

- name: Install acl
  package:
    name:
      - acl
    state: present
  become: yes
  when: ansible_os_family == 'Debian'

- name: Install developer tools
  package:
    name: "{{ devtools }}"
    state: present
  become: yes

- name: Install hardware tools
  package:
    name: "{{ hwtools }}"
    state: present
  become: yes
  tags:
    - hardware

- name: Install GUI programs
  package:
    name:
      - pavucontrol
      - okular
      - feh
      - mpv
    state: present
  become: yes
  tags:
    - gui

      # TODO reorganize
