- name: Set locale in locale.gen
  lineinfile:
    path: /etc/locale.gen
    regexp: "^#en_US.UTF-8 UTF-8"
    line: "en_US.UTF-8 UTF-8"
  become: yes
  when: ansible_distribution == 'Archlinux'

- name: Generate locale
  command: locale-gen
  become: yes
  when: ansible_distribution == 'Archlinux'

- name: Set LANG
  copy:
    content: "LANG=en_US.UTF-8"
    dest: /etc/locale.conf
  become: yes
  when: ansible_distribution == 'Archlinux'

- name: Set timezone
  file:
    src: /usr/share/zoneinfo/Europe/Oslo
    dest: /etc/localtime
    state: link
    force: yes
  become: yes
