- block:
  - import_tasks: install.yml
    tags:
      - install
      - urxvt.install
  - import_tasks: configure.yml
    tags:
      - configure
      - urxvt.configure
  tags:
    - urxvt
    - gui

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - urxvt.uninstall
