# TODO install in home dir


- name: Create dir /etc/vim
  file:
    path: /etc/vim/
    state: directory
  become: yes

- name: Install main vimrc
  copy:
    src: etc/vimrc
    dest: /etc/
  become: yes

- name: Install vimrc sub files
  copy:
    src: "{{ item }}"
    dest: /etc/vim/
  become: yes
  loop:
    - etc/vim/keybinds.vim
    - etc/vim/plugins.vim
    - etc/vim/nerdtree.vim
    - etc/vim/completion.vim

- name: Ensure /etc/xdg/nvim exists
  file:
    dest: /etc/xdg/nvim/
    state: directory
  become: yes

- name: Link vimrc to neovim sysinit.vim
  file:
    src: /etc/vimrc
    dest: /etc/xdg/nvim/sysinit.vim
    state: link
    force: yes
  become: yes

    # TODO maybe set this in ~/.bash_profile instead
- name: Set nvim as EDITOR and VISUAL
  copy:
    src: etc/profile.d/editor.sh
    dest: /etc/profile.d/editor.sh
  become: yes
  when: ansible_distribution != 'FreeBSD'

- name: Set nvim as EDITOR and VISUAL for zsh
  copy:
    src: etc/zsh/zshenv
    dest: /etc/zsh/zshenv
  become: yes
  when: "'zsh' in role_names"

- name: Create vim autoload dir
  file:
    dest: /etc/vim/autoload/
    state: directory
  become: yes

- name: Install plug.vim
  copy:
    src: etc/vim/autoload/plug.vim
    dest: /etc/vim/autoload/plug.vim
    force: no
  become: yes
  tags:
    plugins
    neovim.plugins

    # TODO maybe disable plugins for root
- name: Install neovim plugins for root
  command: nvim +PlugInstall! +PlugUpgrade! +PlugClean! +PlugUpdate! +qa! --headless
  become: yes
  tags:
    plugins
    neovim.plugins

- name: Install neovim plugins for {{ username }}
  command: nvim +PlugInstall! +PlugUpgrade! +PlugClean! +PlugUpdate! +qa! --headless
  become: yes
  become_user: "{{ username }}"
  tags:
    plugins
    neovim.plugins
