- name: Install neovim
  package:
    name:
      - neovim
    state: present
  become: yes

- name: Install pynvim
  pip:
    name:
      - pynvim
    state: present
  become: yes

- name: Install neovim-remote
  pip:
    name:
      - neovim-remote
    state: present
  become: yes

- name: Install xclip
  package:
    name:
      - xclip
    state: present
  become: yes
  tags:
    - gui

- name: Install python language server
  pip:
    name:
      - "python-lsp-server[all]"
    state: present
  become: yes
  tags:
    - python
    - lsp

- name: Install vimscript language server and dependencies
  block:
    - name: Install npm
      package:
        name:
          - npm
        state: present
      become: yes

    - name: Install vimscript language server
      npm:
        name: vim-language-server
        global: yes
      become: yes
  tags:
    - vimscript
    - lsp

- name: Install C/C++ language server
  package:
    name:
      - ccls
    state: present
  become: yes
  tags:
    - c
    - cpp
