- name: Install neovim
  package:
    name:
      - neovim
        #- python-pynvim
    state: present
  become: yes

- name: Install xclip
  package:
    name:
      - xclip
    state: present
  become: yes
