---
- block:
  - import_tasks: prepare.yml
    tags:
      - prepare
      - neovim.prepare
  - import_tasks: install.yml
    tags:
      - install
      - neovim.install
  - import_tasks: configure.yml
    tags:
      - configure
      - neovim.configure
  tags:
    - neovim

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - neovim.uninstall
