- name: Create .mutt directory
  file:
    path: /home/{{ username }}/.mutt/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Configure mutt
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.mutt/
  loop:
    - HOME/.mutt/muttrc
    - HOME/.mutt/colors
    - HOME/.mutt/keybinds
    - HOME/.mutt/powerline
  become: yes
  become_user: "{{ username }}"

- name: Add mailcap
  copy:
    src: HOME/.mutt/mailcap
    dest: /home/{{ username }}/.mutt/mailcap
  become: yes
  become_user: "{{ username }}"
