- name: Create .mutt directory
  file:
    path: /home/{{ username }}/.mutt/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Create muttrc
  template:
    src: HOME/.mutt/muttrc.j2
    dest: /home/{{ username }}/.mutt/muttrc
  become: yes
  become_user: "{{ username }}"

- name: Configure mutt
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.mutt/
  loop:
    - HOME/.mutt/colors
    - HOME/.mutt/keybinds
    - HOME/.mutt/powerline
  become: yes
  become_user: "{{ username }}"

- name: Create .mutt/accounts directory
  file:
    path: /home/{{ username }}/.mutt/accounts/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Configure email accounts in mutt
  template:
    src: HOME/.mutt/account.j2
    dest: /home/{{ username }}/.mutt/accounts/{{ email.account_name }}
  become: yes
  become_user: "{{ username }}"
  loop: "{{ email_accounts }}"
  loop_control:
    loop_var: email

- name: Add mailcap
  copy:
    src: HOME/.mutt/mailcap
    dest: /home/{{ username }}/.mutt/mailcap
  become: yes
  become_user: "{{ username }}"
