- name: Create .config/neomutt directory
  file:
    path: /home/{{ username }}/.config/neomutt/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Create muttrc
  template:
    src: HOME/.config/neomutt/muttrc.j2
    dest: /home/{{ username }}/.config/neomutt/muttrc
  become: yes
  become_user: "{{ username }}"

- name: Configure mutt
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.config/neomutt/
  loop:
    - HOME/.config/neomutt/colors
    - HOME/.config/neomutt/keybinds
    - HOME/.config/neomutt/powerline
  become: yes
  become_user: "{{ username }}"

- name: Create .config/neomutt/accounts directory
  file:
    path: /home/{{ username }}/.config/neomutt/accounts/
    state: directory
  become: yes
  become_user: "{{ username }}"

- name: Configure email accounts in mutt
  template:
    src: HOME/.config/neomutt/account.j2
    dest: /home/{{ username }}/.config/neomutt/accounts/{{ email.account_name }}
  become: yes
  become_user: "{{ username }}"
  loop: "{{ email_accounts }}"
  loop_control:
    loop_var: email

- name: Add mailcap
  copy:
    src: HOME/.config/neomutt/mailcap
    dest: /home/{{ username }}/.config/neomutt/mailcap
  become: yes
  become_user: "{{ username }}"

- name: Add account switching script
  copy:
    src: HOME/.config/neomutt/switchaccount.sh
    dest: /home/{{ username }}/.config/neomutt/switchaccount.sh
    mode: '0700'
  become: yes
  become_user: "{{ username }}"
