---
- block:
  - import_tasks: install.yml
    tags:
      - install
      - neomutt.install
  - import_tasks: configure.yml
    tags:
      - configure
      - neomutt.configure
  tags:
    - neomutt
    - mail

- import_tasks: clean.yml
  tags:
    - never
    - clean
    - neomutt.clean

- import_tasks: uninstall.yml
  tags:
    - never
    - uninstall
    - neomutt.uninstall
